### ISSUE TITLE
URGENT : Problem when loading data on an Hbase Cluster managed by Cloudera Manager 6.3 

### ISSUE THREAD

**Issue by Panongbene** [Panongbene/technologie-issues-solves#1]
# URGENT : Problem when loading data on an Hbase Cluster managed by Cloudera Manager 6.3 

To load data from an Oracle database to Hbase, we have developed a Talend Job which browses the tables incrementally using a primary key shared between the tables, when the talend job is launched on a server remote from the two databases (Hbase and Oracle) hbase regions servers fail after a few minutes of loading.

The volume of data is large without being intractable, the description of the cluster is visible in the following diagrams.
![1](https://user-images.githubusercontent.com/55893321/173613802-e7f9b1aa-2fca-46ae-86b9-3b73fe571b47.png)
![2](https://user-images.githubusercontent.com/55893321/173613857-47a12dbe-77ed-479f-9583-cd4be3b5cefb.PNG)
![3](https://user-images.githubusercontent.com/55893321/173613875-20615cc5-4096-48ab-919c-959fc3c5e5a5.PNG)
![4](https://user-images.githubusercontent.com/55893321/173613901-f8f22ab7-bba6-41ed-9ee6-bb1252036dae.png)
![5](https://user-images.githubusercontent.com/55893321/173613919-65d425c3-b0ae-46b7-bbfc-9fbca47ef073.png)
![6](https://user-images.githubusercontent.com/55893321/173613942-0c86c05c-07c2-41c3-b6f5-a2b748a6e295.png)

**Comment by Panongbene** [comment]
#URGENT LIMITED == 15h -- 15/06/2022

**Comment by a17t** [comment]
Hello,
I stumbled upon your issue on bountysource. Tbh from what you provide it is guesswork what might be the cause. Although I have some possible causes in mind.

As this affects one of your (live) systems, what process do you have in mind to solve this?

**Comment by Panongbene** [comment]
Isssue resolved
